language: ruby
rvm:
  - 2.5
env:
  - JEKYLL_ENV=production
install:
  - bundle install --jobs=3 --retry=3
  - yarn
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: _site
  on:
    branch: site
  target-branch: master
cache:
  - bundler
  - yarn
