# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joren Van Hee
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joren.co" # the base hostname & protocol for your site
twitter_username: jorenvanhee
github_username: jorenvanhee

# Collections
collections:
  projects:
    output: false
  posts:
    output: true
    permalink: /:title/

# Build settings
markdown: kramdown
exclude: [
  'tags',
  'node_modules',
  'package.json',
  'tailwind.js',
  'yarn.lock',
  'webpack.config.js',
  'postcss.config.js',
  '_assets',
  'Gemfile',
  'Gemfile.lock',
]
keep_files: [
  'dist',
]
